#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

gmsh - tube.geo
gmshToFoam tube.msh
cp -r 0.org 0
changeDictionary

# ----------------------------------------------------------------- end-of-file
